// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Rajdhani, Inter } from "next/font/google";
import Script from "next/script";
import { Toaster } from "sonner";
import "./globals.css";

const rajdhani = Rajdhani({
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-rajdhani",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Super SandPlay - Beach Tennis",
  description: "Gerenciamento Profissional de Disputas de Beach Tennis com Precisão Absoluta",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body
        className={`${rajdhani.variable} ${inter.variable} antialiased bg-gradient-to-br from-[#1a0a1f] via-[#2d1b3d] to-[#1a0a1f] font-inter`}
      >
        {children}
        <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}
